using System;
using System.Collections.Generic;
using System.Linq;

namespace MondainDeploy
{
    /// <summary>
    /// Summary description for Quiz
    /// </summary>
    [Serializable]
    public class Quiz
    {
        public int QuizLength { get; set; }
        public int QuestionNumber { get; set; }
        public KeyValuePair<string, List<string>> CurrentQuestion { get; set; }
        public List<WordData> CurrentAnswerResultsList;

        public List<QuizAnswer> CurrentQuizAnswerStatsList;

        public List<string> CurrentAnswerList { get; set; }

        public List<KeyValuePair<string, List<string>>> QuizAlphaToWords { get; set; }

        public int CorrectAlphagramCount;
        public int IncorrectAlphagramCount;
        public int CorrectWordCount, IncorrectWordCount, CurrentAnswerWordCount;
        public bool Finished { get; set; }
        public bool IsBlankBingos { get; set; }
        public bool ShowLexSymbols { get; set; }

        /// <summary>
        /// Constructor for new quiz.
        /// </summary>
        /// <param name="quizLength">Length of quiz.</param>
        /// <param name="quizAlphaToWords">List of question/answers key-value pairs, generated by a FullLexicon object.</param>
        /// <param name="isBlankBingos">Whether the current quiz is in blank bingo mode.</param>
        /// <param name="questionNumber">Ordinal position in quiz, starting from 1. Default value is 1.</param>
        public Quiz(int quizLength, List<KeyValuePair<string, List<string>>> quizAlphaToWords, bool isBlankBingos, bool showLexSymbols, int questionNumber = 1)
        {
            QuizLength = quizLength;
            QuestionNumber = questionNumber;
            QuizAlphaToWords = quizAlphaToWords;
            IsBlankBingos = isBlankBingos;
            CurrentQuestion = QuizAlphaToWords[QuestionNumber - 1];
            CurrentAnswerList = QuizAlphaToWords[QuestionNumber - 1].Value;
            CurrentAnswerWordCount = QuizAlphaToWords[QuestionNumber - 1].Value.Count;
            CorrectAlphagramCount = IncorrectAlphagramCount = CorrectWordCount = IncorrectWordCount = 0;
            ShowLexSymbols = showLexSymbols;
            Finished = false;

            CurrentQuizAnswerStatsList = new List<QuizAnswer>();
            foreach (var str in CurrentAnswerList)
            {
                CurrentQuizAnswerStatsList.Add(new QuizAnswer(str, false));
            }

        }

        /// <summary>
        /// Marks a single word in a quiz as correctly answered.
        /// </summary>
        /// <param name="word">A single solution to an alphagram.</param>
        public void SetWordAsCorrect(string word)
        {
            foreach (var kvp in CurrentQuizAnswerStatsList.Where(kvp => kvp.Word == word))
            {
                kvp.IsCorrect = true;
            }
        }

        /// <summary>
        /// Resets the # of answers and correct/incorrect stats when starting a new question.
        /// </summary>
        public void ResetCurrentAnswerStats()
        {
            CurrentAnswerWordCount = QuizAlphaToWords[QuestionNumber - 1].Value.Count;

            CurrentQuizAnswerStatsList = new List<QuizAnswer>();


            

            foreach (var str in CurrentAnswerList)
            {
                CurrentQuizAnswerStatsList.Add(new QuizAnswer(str, false));
            }

        }


        /// <summary>
        /// Depending on if the question was correct, increases the correct or incorrect alphagram stats count.
        /// </summary>
        /// <param name="isCorrect">Whether or not the answer was correct.</param>
        public void IncrementCounts(bool isCorrect)
        {
            if (isCorrect)
                CorrectAlphagramCount++;
            else
                IncorrectAlphagramCount++;
        }


        /// <summary>
        /// Retrieve an array consisting of the correct and incorrect answers on the current alphagram/question.
        /// </summary>
        public int[] GetBooleanAnswersThisQuestion()
        {
            int[] correct = { 0, 0 };
            foreach (var kvp in CurrentQuizAnswerStatsList)
            {
                if (kvp.IsCorrect)
                    correct[0]++;
                else
                    correct[1]++;
            }
            return correct;
        }


    }

    [Serializable]
    public class QuizAnswer
    {
        public string Word { get; set; }
        public string WordDisplayString { get; set; }
        public bool IsCorrect { get; set; }

        /// <summary>
        /// QuizAnswer 2-argument constructor. Sets WordDisplayString and Word equal, otherwise params = input.
        /// </summary>
        /// <param name="word">An individual solution to an alphagram.</param>
        /// <param name="isCorrect">Whether the word has been answered correctly.</param>
        public QuizAnswer(string word, bool isCorrect)
        {
            Word = word;
            WordDisplayString = word;
            IsCorrect = isCorrect;
        }

        ///// <summary>
        ///// QuizAnswer 3-argument constructor. For use when WordDisplayString should be specified explicitly.
        ///// </summary>
        ///// <param name="word">An individual solution to an alphagram.</param>
        ///// <param name="isCorrect">Whether the word has been answered correctly.</param>
        ///// <param name="wordDisplayString">Word with lexicon symbols in use.</param>
        //public QuizAnswer(string word, bool isCorrect, string wordDisplayString)
        //{
        //    Word = word;
        //    WordDisplayString = wordDisplayString;
        //    IsCorrect = isCorrect;
        //}
    }
}